import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import NavigationBar from "@/components/NavigationBar";
import { auth } from "@/auth";
import AuthNavigationBar from "@/components/AuthNavigationBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="w-screen h-dvh bg-gradient-to-r from-blue-200 to-cyan-200 p-8">
          {session ? <NavigationBar /> : <AuthNavigationBar />}
          {children}
        </main>
        <Toaster richColors />
      </body>
    </html>
  );
}
